-- Migration: Add incremental 'number' column to public.executions starting at 1

ALTER TABLE public.executions
  ADD COLUMN IF NOT EXISTS number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1);
